/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import com.gargoylesoftware.htmlunit.ElementNotFoundException
import it.skrape.core.*
import it.skrape.fetcher.*
import it.skrape.selects.html5.*
import android.os.Environment
import java.io.File
import java.io.FileWriter
import java.io.IOException

//fun main() {
//    println(App().greeting)
//}

data class MenuItem(
    var name: String = "",
    var url: String = "",
    var description: String = ""
)

fun main() {
    val menuItems: ArrayList<MenuItem> = skrape(HttpFetcher) {
        // perform a GET request to the specified URL
        request {
            url = "http://menu.dining.ucla.edu/Menus/FeastAtRieber"
        }

        extractIt<ArrayList<MenuItem>> {
            htmlDocument {
                var duplicate = false
                "div.menu-item,div.menu-block,div.menu-block-fullwidth" { // CSS selector for menu items
                    findAll {
                        forEach {menuItemElement ->
                            try {
                                val day =
                                    menuItemElement.h2 { findFirst { text } }
                                val menuItem = MenuItem(name=day, url=day, description=day)
                                it.add(menuItem)
                                duplicate = true
                            } catch(e: Throwable) {

                            }
                            try {
                                val menuItem = MenuItem(
                                    url = menuItemElement.a { findFirst { attribute("href") } },
                                    name = menuItemElement.a { findFirst { text } },
                                    description = try {
                                        menuItemElement.span(".menu-item-description") { findFirst { text } }
                                    } catch (e: Throwable) {
                                        ""
                                    }
                                )
                                if (!duplicate) {
                                    it.add(menuItem)
                                } else {
                                    duplicate = false
                                }
                            } catch (e: Throwable) {

                            }

                        }
                    }
                    }

            }
        }
    }

    //separate spices from menuitems
    var extras = ArrayList<MenuItem>()
    val daysOfWeek = arrayListOf("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
    var dayIndex = 0
    var firstIndex = -1
    var secondIndex = -1
    //get first day of this week
    while (firstIndex == -1) {
        firstIndex = menuItems.indexOfFirst { it.name.contains(daysOfWeek.get(dayIndex++)) }
    }
    //if not friday, get second day of week and split lists accordingly
    if (dayIndex != 5) {
        secondIndex = menuItems.indexOfFirst { it.name.contains(daysOfWeek.get(dayIndex)) }
        extras = ArrayList<MenuItem>(menuItems.subList(firstIndex + 5 + 1, secondIndex).toList())
    } else { //remove everything after four menu items
        extras = ArrayList(menuItems.subList(firstIndex + 5 + 1, menuItems.size).toList())
    }
    menuItems.removeAll(extras)

//    print each scraped item
    menuItems.forEach {
        if (it.name.contains(daysOfWeek.get(0)) || it.name.contains(daysOfWeek.get(1)) || it.name.contains(daysOfWeek.get(2)) || it.name.contains(daysOfWeek.get(3)) || it.name.contains(daysOfWeek.get(4))) {
            print("Day: ")
            println(it.name)
        }
        else {
            println("MenuItem:")
            println(it)
        }
    }
//    println(extras)
//    println(menuItems)
}

fun writeDataToCsv(data: ArrayList<MenuItems>, toppings: ArrayList<MenuItems>) {

}